export default [
    {
        id: 1,
        "name" : "Anya Black Shoes EasySoft World Balance !!",
        "img" : "https://lzd-img-global.slatic.net/g/p/6f0a7f0690fb592acef92ba464604bc7.jpg_720x720q80.jpg",
        "location" : "Malabon City",
        "rate" : "4.3 / 5",
        "sold" : "49",
        "favorites" : "21",
        "heart" : "0",
        "color" : ["black", "white"],
        "size" : ["29","30","31", "32","33","34", "35", "36"],
        "isheart" : false,
        "price" : "599.00",
        "sale" : "500.00",
        "category" : ["Female"],
        "tags" : ["most heart", "sale"] 
    },
    {
        id: 2,
        "name" : "Atlanta",
        "img" : "https://ph-test-11.slatic.net/p/525e257e92b6a33189b58f63d2ad83cf.jpg",
        "location" : "Malabon City",
        "rate" : "4.3 / 5",
        "heart" : "0",
        "color" : ["black", "white"],
        "size" : ["39","40","41", "42","43","44", "45"],
        "sold" : "49",
        "favorites" : "21",
        "isheart" : false,
        "price" : "599.00",
        "sale" : "500.00",
        "category" : ["Men"],
        "tags" : ["trending", "sale"]
    },
    {
        id: 3,
        "name" : "Basel",
        "img" : "https://ph-live-01.slatic.net/p/fddb9f5a9131e5f52266f8e3fb07047e.jpg",
        "location" : "Malabon City",
        "rate" : "4.3 / 5",
        "heart" : "0",
        "sold" : "49",
        "favorites" : "21",
        "color" : ["black"],
        "size" : ["39","40","41", "42","43","44", "45"],
        "isheart" : false,
        "price" : "599.00",
        "category" : ["Men"],
        "tags" : ["most heart"]
    },
    {
        id: 4,
        "name" : "Black Hawk",
        "img" : "https://media.karousell.com/media/photos/products/2022/8/5/easysoft_blackhawk_bb_1659691186_7d0c81f4_progressive",
        "location" : "Malabon City",
        "rate" : "4.3 / 5",
        "heart" : "0",
        "favorites" : "21",
        "sold" : "49",
        "color" : ["black"],
        "size" : ["39","40","41", "42","43","44", "45"],
        "isheart" : false,
        "price" : "599.00",
        "category" : ["Men"],
        "tags" : ["trending","Most Heart"], 
    },
    {
        id: 5,
        "name" : "British",
        "img" : "https://ph-test-11.slatic.net/p/26a0f2ed6798aba1768c7ae88fd3f38c.jpg",
        "location" : "Malabon City",
        "rate" : "4.3 / 5",
        "heart" : "0",
        "favorites" : "21",
        "sold" : "49",
        "color" : ["black"],
        "size" : ["39","40","41", "42","43","44", "45"],
        "isheart" : true,
        "price" : "599.00",
        "category" : ["Men"],
        "tags" : ["trending"] 
    },
    {
        id: 6,
        "name" : "Brooklyn",
        "img" : "https://easysoft.com.ph/cdn/shop/products/0096_brooklyn_blk_iso_2_2_1445x.jpg?v=1650608887",
        "location" : "Malabon City",
        "rate" : "4.3 / 5",
        "heart" : "0",
        "sold" : "49",
        "color" : ["black"],
        "size" : ["39","40","41", "42","43","44", "45"],
        "favorites" : "21",
        "isheart" : false,
        "price" : "599.00",
        "sale" : "500.00",
        "category" : ["Men"],
        "tags" : ["sale"] 
    }
]